### ISSUE TITLE
Does not work in remote SSH mode?

### ISSUE THREAD

**Issue by alexandroid** [SmartyTomato/SmartOpen#24]
**Describe the bug**
I am using VSCode in ["Remote SSH" mode](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) and have installed this extension in remote mode as well. Pressing `Ctrl+Alt+;` does not seem to work in this case. It works fine in a local mode (when VSCode and extensions are working with local files), so it's not an issue of the keyboard binding misconfiguration.

**To Reproduce**
1. Install https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
2. Set up remote Linux machine following the instructions from #1 (it installs VSCode server under the hood)
3. Open a repository in SSH mode.
3. Install SmartOpen extension in remote VSCode as well (relaunch VSCode after)
4. Open any file in the explorer, scroll away from it and press `Ctrl+Alt+;` - the explorer window is focused but not scrolled to the opened file

**Expected behavior**
Similar to the local behavior - pressing `Ctrl+Alt+;` opens and scrolls Explorer to the currently opened file.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows VSCode client, Linux VSCode remote
 - Version - VSCode 1.43.2, SmartOpen 1.6.4

**Comment by tommywkzhao** [comment]
Hi, thanks for submitting the issue report. 

Unfortunately, I couldn't make the SSH working with VSCode on my machine. I think there is a way around if you simply want use the shortcut. Check this if it is work for you.
The shortcut calling one of the existing command in the vscode, you can try following step to directly setup "keyboard shortcut".

- In vscode, open Keyboard Shortcuts
- Search for `workbench.files.action.showActiveFileInExplorer`
- Set a shortcut. Try if it works for the SSH. 

If it is still not working, then I couldn't do anything because it is not a customizable thing. Internally, the `Ctrl+Alt+;` calls this command

**Comment by alexandroid** [comment]
I don't know what changed, but suddenly today the shortcuts started working even in remote mode. Apologies for the churn!

**Comment by tommywkzhao** [comment]
Maybe other extension updated. I see the remote SSH is still in beta, maybe some issue there. Enjoy your coding👍
